project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Ava A. H. Ortiz"
  date: today
  reader-mode: true
  page-navigation: true
  back-to-top-navigation: true
  bread-crumbs: true
  
  
  sidebar:
    title: "Ava A. H. Ortiz"
    collapse-level: 2
    style: "docked"
    pinned: true
    search: true
  
  
  chapters:
    - index.qmd
    #- hw/hw0.qmd
    #- hw/hw1.qmd

    - part: "Best Work"
      chapters: 
      - bw/bw-uni.qmd
      - bw/bw-bi.qmd
      - bw/bw-tri.qmd
      - bw/bw-quad.qmd
      - bw/bw-spatial.qmd
      - bw/Exam1.qmd
      - bw/Exam2.qmd
      - bw/SoloProject.qmd

    - part: "Summaries"
      chapters:
      - Summary/Exam1_Summary.qmd
      - Summary/Exam2_Summary.qmd
    
    - part: "In-class Activities"
      chapters: 
      - ica/quarto-demo.qmd
      - ica/ica-uni.qmd
      - ica/ica-bi.qmd
      - ica/ica-multi.qmd
      - ica/ica-spatial.qmd
      - ica/ica-wrangling.qmd
      - ica/ica-dates.qmd
      - ica/ica-reshaping.qmd
      - ica/ica-joining.qmd
      - ica/ica-factors.qmd
      - ica/ica-Strings.qmd
      - ica/ica-dataimport.qmd
    

format:
  html:
    theme:
      light: flatly
      dark: darkly
    toc: true
    toc-depth: 3
    link-external-newwindow: true
    css: style/custom.css
    code-copy: true
    code-link: true
    code-line-numbers: true
    code-tools: true
    code-fold: true

execute:
  echo: true
  warning: false
  error: false
  cache: false
  freeze: auto
    
editor: 
  markdown:
    wrap: sentence # Forces each sentence to be on its own line in source markdown, however, it doesn't affect how it is rendered
